Traceback (most recent call last):
  File "/home/lw/venv-ngbem/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/lw/venv-ngbem/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lw/venv-ngbem/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/lw/venv-ngbem/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/lw/venv-ngbem/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/lw/venv-ngbem/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
V = MaxwellSingleLayerPotentialOperator(fesHDiv, kappa, intorder=10, leafsize=40, eta=3., eps=1e-4)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m V [38;5;241m=[39m [43mMaxwellSingleLayerPotentialOperator[49m[43m([49m[43mfesHDiv[49m[43m,[49m[43m [49m[43mkappa[49m[43m,[49m[43m [49m[43mintorder[49m[38;5;241;43m=[39;49m[38;5;241;43m10[39;49m[43m,[49m[43m [49m[43mleafsize[49m[38;5;241;43m=[39;49m[38;5;241;43m40[39;49m[43m,[49m[43m [49m[43meta[49m[38;5;241;43m=[39;49m[38;5;241;43m3.[39;49m[43m,[49m[43m [49m[43meps[49m[38;5;241;43m=[39;49m[38;5;241;43m1e-4[39;49m[43m)[49m

[0;31mTypeError[0m: MaxwellSingleLayerPotentialOperator(): incompatible function arguments. The following argument types are supported:
    1. (space: ngcomp::FESpace, kappa: float, definedon: Optional[ngcomp::Region] = None, intorder: int = 3, leafsize: int = 40, eta: float = 2.0, eps: float = 1e-06, method: str = 'aca', testhmatrix: bool = False) -> ngbem._ngbem.IntegralOperatorC

Invoked with: <ngsolve.comp.HDivSurface object at 0x7fd04e9bffb0>, 5.0034083602476045; kwargs: intorder=10, leafsize=40, eta=3.0, eps=0.0001

